// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEahUFz80iO9tlj_IpJ_5jAJGhpQMdBSI',
    appId: '1:822633319324:web:e579641b702250dd3a1659',
    messagingSenderId: '822633319324',
    projectId: 'rehberuygulamam',
    authDomain: 'rehberuygulamam.firebaseapp.com',
    storageBucket: 'rehberuygulamam.firebasestorage.app',
    measurementId: 'G-NY6YYEXZYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjU1kAKz3Yp3WhhZ4arsHDULzGy2Izhtc',
    appId: '1:822633319324:android:aacbfc73ce983e053a1659',
    messagingSenderId: '822633319324',
    projectId: 'rehberuygulamam',
    storageBucket: 'rehberuygulamam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAijcITHM0GQBsOeZpXy49YlMyAN2H3t5c',
    appId: '1:822633319324:ios:e57fe4dcfb4c67b33a1659',
    messagingSenderId: '822633319324',
    projectId: 'rehberuygulamam',
    storageBucket: 'rehberuygulamam.firebasestorage.app',
    iosBundleId: 'com.example.telefonRehberi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAijcITHM0GQBsOeZpXy49YlMyAN2H3t5c',
    appId: '1:822633319324:ios:e57fe4dcfb4c67b33a1659',
    messagingSenderId: '822633319324',
    projectId: 'rehberuygulamam',
    storageBucket: 'rehberuygulamam.firebasestorage.app',
    iosBundleId: 'com.example.telefonRehberi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEahUFz80iO9tlj_IpJ_5jAJGhpQMdBSI',
    appId: '1:822633319324:web:da16e981ed9e4ff83a1659',
    messagingSenderId: '822633319324',
    projectId: 'rehberuygulamam',
    authDomain: 'rehberuygulamam.firebaseapp.com',
    storageBucket: 'rehberuygulamam.firebasestorage.app',
    measurementId: 'G-QSPY9XRNR8',
  );
}
